'use strict';
// Palabras cotidianas y pistas amplias para que los niños puedan participar.
const words=[
['Helado','Algo frío'],['Pizza','Algo para compartir'],['Queso','Algo que se come'],['Chocolate','Algo dulce'],['Pan','Puede estar calientito'],['Manzana','Algo que crece en una planta'],['Cambur','Algo que se pela'],['Patilla','Algo que tiene semillas'],['Galleta','Algo que puede crujir'],['Torta','Algo para celebrar'],['Cotufas','Algo para una merienda'],['Huevo','Algo que se puede cocinar'],['Espagueti','Algo que se come en un plato'],['Arepa','Algo para desayunar'],['Jugo','Algo que se toma'],['Leche','Algo que va en un vaso'],['Zanahoria','Algo que crece en la tierra'],['Limón','Algo de sabor fuerte'],['Fresa','Algo pequeño que se come'],['Arroz','Algo que acompaña una comida'],
['Perro','Un compañero'],['Gato','Un animal de casa'],['Elefante','Un animal grande'],['León','Un animal salvaje'],['Jirafa','Un animal alto'],['Mono','Un animal que trepa'],['Conejo','Un animal con pelo'],['Tortuga','Un animal tranquilo'],['Pez','Un animal que se mueve en el agua'],['Delfín','Un animal del mar'],['Mariposa','Algo que vuela'],['Abeja','Un animal pequeño'],['Hormiga','Un animal que trabaja en grupo'],['Caballo','Un animal fuerte'],['Vaca','Un animal del campo'],['Cerdo','Un animal de una granja'],['Pato','Un animal que puede nadar'],['Gallina','Un animal con plumas'],['Oso','Un animal con mucho pelo'],['Tiburón','Un animal que vive en el agua'],
['Zapato','Algo que te pones'],['Sombrero','Algo para vestirse'],['Camisa','Algo de un armario'],['Pijama','Algo cómodo'],['Medias','Algo que suele ir en pareja'],['Mochila','Algo para llevar cosas'],['Paraguas','Algo para protegerte'],['Cepillo de dientes','Algo de todos los días'],['Jabón','Algo que se usa con agua'],['Toalla','Algo del baño'],['Cama','Algo para descansar'],['Almohada','Algo suave'],['Silla','Algo que tiene patas'],['Mesa','Algo de la casa'],['Nevera','Algo de la cocina'],['Cuchara','Algo que usas para comer'],['Tenedor','Algo que está en la mesa'],['Vaso','Algo que se puede llenar'],['Reloj','Algo que miras'],['Llave','Algo pequeño y útil'],['Teléfono','Algo para comunicarse'],['Televisor','Algo para entretenerse'],['Libro','Algo que puedes abrir'],['Lápiz','Algo para crear'],['Tijera','Algo para hacer manualidades'],['Espejo','Algo que miras de cerca'],['Escoba','Algo para limpiar'],['Puerta','Algo que se abre'],['Ventana','Algo por donde puedes mirar'],['Lámpara','Algo que sirve de noche'],
['Playa','Un lugar para pasear'],['Piscina','Un lugar para divertirse'],['Parque','Un lugar al aire libre'],['Colegio','Un lugar para aprender'],['Cine','Un lugar al que vas con otros'],['Supermercado','Un lugar para comprar'],['Hospital','Un lugar donde ayudan'],['Cocina','Un lugar de la casa'],['Baño','Un lugar que usas a diario'],['Jardín','Un lugar con vida'],
['Bicicleta','Algo para moverte'],['Avión','Algo para viajar'],['Carro','Algo que lleva personas'],['Barco','Algo para un viaje'],['Tren','Algo que lleva a mucha gente'],['Autobús','Algo que hace paradas'],['Pelota','Algo para jugar'],['Columpio','Algo que se mueve'],['Tobogán','Algo de un parque'],['Globo','Algo para una fiesta'],['Regalo','Algo que da alegría'],['Cumpleaños','Un día especial'],['Navidad','Una celebración'],['Piñata','Algo de una fiesta'],['Robot','Algo que se mueve'],['Muñeca','Algo para jugar en casa'],['Rompecabezas','Algo para armar'],['Cometa','Algo para usar afuera'],['Guitarra','Algo que hace sonidos'],['Tambor','Algo para hacer música'],
['Sol','Algo en el cielo'],['Luna','Algo que ves de noche'],['Estrella','Algo que está lejos'],['Nube','Algo que cambia de forma'],['Lluvia','Algo que viene del cielo'],['Nieve','Algo de un lugar frío'],['Arcoíris','Algo que puedes ver afuera'],['Árbol','Algo que crece'],['Flor','Algo de la naturaleza'],['Montaña','Algo que puedes visitar'],['Río','Algo que se mueve'],['Arena','Algo que puedes tocar'],['Piedra','Algo duro'],['Fuego','Algo que da calor'],['Hielo','Algo que cambia con el calor']
];
const hardWords=[["Esfera celeste", "Un modelo para estudiar el cielo"], ["Sextante", "Un instrumento para orientarse"], ["Metrónomo", "Algo que marca un ritmo"], ["Reloj de arena", "Algo que mide el paso del tiempo"], ["Caleidoscopio", "Algo que cambia lo que ves"], ["Reloj de sol", "Algo que depende de la luz"], ["Ábaco", "Algo para hacer cuentas"], ["Giroscopio", "Algo relacionado con el equilibrio"], ["Esfera armilar", "Un modelo del cielo"], ["Clavecín", "Un instrumento musical antiguo"], ["Obelisco", "Una construcción alta"], ["Acueducto", "Una construcción para transportar algo"], ["Gárgola", "Algo en un edificio antiguo"], ["Sarcófago", "Algo del pasado"], ["Catapulta", "Algo que lanza objetos"], ["Puente colgante", "Una construcción para cruzar"], ["Observatorio", "Un lugar para investigar"], ["Brújula", "Algo para orientarse"], ["Anemómetro", "Algo que mide la naturaleza"], ["Periscopio", "Algo para mirar desde otro lugar"]];
const cultureWords=[["Lionel Messi", "Una persona del deporte", "⚽"], ["Cristiano Ronaldo", "Una persona que compite", "⚽"], ["Simón Bolívar", "Una persona de la historia", "📜"], ["Frida Kahlo", "Una persona que creaba arte", "🎨"], ["Albert Einstein", "Una persona que investigaba", "🔬"], ["Marie Curie", "Una persona de la ciencia", "🧪"], ["Leonardo da Vinci", "Una persona con muchas ideas", "🎨"], ["Beethoven", "Una persona que creaba música", "🎼"], ["Neil Armstrong", "Una persona que exploraba", "👨‍🚀"], ["Walt Disney", "Una persona del entretenimiento", "🎬"], ["Venezuela", "Un país de América", "🇻🇪"], ["Brasil", "Un país con mucha naturaleza", "🇧🇷"], ["Japón", "Un país de Asia", "🇯🇵"], ["Egipto", "Un país con mucha historia", "🇪🇬"], ["Italia", "Un país de Europa", "🇮🇹"], ["Francia", "Un país con mucho arte", "🇫🇷"], ["México", "Un país con muchas tradiciones", "🇲🇽"], ["Argentina", "Un país de América del Sur", "🇦🇷"], ["China", "Un país muy grande", "🇨🇳"], ["Australia", "Un país lejos de América", "🇦🇺"], ["Torre Eiffel", "Una construcción famosa", "🗼"], ["Pirámides de Egipto", "Unas construcciones antiguas", "🏜️"], ["Gran Muralla China", "Una construcción muy larga", "🧱"], ["Taj Mahal", "Un monumento famoso", "🕌"], ["Coliseo romano", "Un lugar antiguo para espectáculos", "🏛️"], ["Saturno", "Algo que está en el espacio", "🪐"], ["Júpiter", "Algo muy grande en el espacio", "🟠"], ["Marte", "Un lugar que se investiga", "🔴"], ["Volcán", "Algo de la naturaleza", "🌋"], ["Océano", "Algo que cubre parte de la Tierra", "🌊"]];
const curiousFacts={"Albert Einstein": ["Recibió el Nobel de Física de 1921 por explicar un fenómeno de la luz llamado efecto fotoeléctrico.", "https://www.nobelprize.org/prizes/physics/the-dual-nature-of-light-as-reflected-in-the-nobel-archives/", "Nobel Prize"], "Marie Curie": ["Ganó dos premios Nobel: uno de Física y otro de Química.", "https://www.nobelprize.org/prizes/themes/the-nobel-prize-in-physics-1901-2000/", "Nobel Prize"], "Brasil": ["Es el país más grande de América del Sur. Su idioma oficial es el portugués.", "https://kids.nationalgeographic.com/geography/countries/article/brazil", "National Geographic Kids"], "Japón": ["Es un archipiélago: un país formado por un conjunto de islas. Está en Asia.", "https://kids.nationalgeographic.com/geography/countries/article/japan", "National Geographic Kids"], "Egipto": ["Las famosas pirámides de Guiza están cerca de El Cairo, la capital del país.", "https://kids.nationalgeographic.com/geography/countries/article/egypt", "National Geographic Kids"], "Italia": ["Si miras su mapa, la península italiana tiene una forma que recuerda a una bota.", "https://kids.nationalgeographic.com/geography/countries/article/italy", "National Geographic Kids"], "Pirámides de Egipto": ["En Guiza también está la Gran Esfinge, una enorme escultura construida por los antiguos egipcios.", "https://kids.nationalgeographic.com/geography/countries/article/egypt", "National Geographic Kids"], "Gran Muralla China": ["No se construyó de una sola vez: distintas generaciones la ampliaron durante muchos siglos.", "https://whc.unesco.org/en/list/438/", "UNESCO"], "Taj Mahal": ["Está en la India y es famoso por su mármol blanco y sus jardines.", "https://whc.unesco.org/en/list/252/", "UNESCO"], "Coliseo romano": ["Los romanos lo construyeron hace casi 2.000 años para reunir a miles de personas en espectáculos.", "https://kids.nationalgeographic.com/geography/countries/article/italy", "National Geographic Kids"], "Saturno": ["Sus anillos están hechos de muchísimos fragmentos de hielo y roca. No son una pieza sólida.", "https://science.nasa.gov/saturn/facts/", "NASA"], "Júpiter": ["Es el planeta más grande del sistema solar. Allí un día dura aproximadamente 10 horas.", "https://science.nasa.gov/jupiter/jupiter-facts/", "NASA"], "Marte": ["Su color rojizo se debe a minerales de hierro que se oxidan, parecido a lo que ocurre con una pieza de hierro.", "https://science.nasa.gov/mars/facts/", "NASA"], "Luna": ["Tarda unos 27 días en dar una vuelta a la Tierra y gira sobre sí misma al mismo ritmo. Por eso vemos casi siempre su misma cara.", "https://science.nasa.gov/moon/facts/", "NASA"]};
function curiousCard(){const fact=curiousFacts[round.word[0]];if(!fact)return "";return `<aside class="curious"><span class="eyebrow">¿Sabías que…?</span><h3>${escape(round.word[0])}</h3><p>${escape(fact[0])}</p><a href="${escape(fact[1])}" target="_blank" rel="noopener noreferrer">Leer más · ${escape(fact[2])}</a></aside>`;}
const avatarLabels=['Astronauta','Alien','Zorro','Panda','Robot','Gato detective','Dinosaurio','Loro pirata','Monstruo','Fantasma','Tigre','Pulpo','Unicornio','Mapache','Rana','Pingüino','León','Oso','Conejo','Búho'];
function avatar(i,big=false){return `<span class="avatar ${big?'large':''}" role="img" aria-label="Avatar: ${avatarLabels[i%20]}" style="background-position:${(i%5)*25}% ${Math.floor((i%20)/5)*100/3}%"></span>`;}
function wordImage(){if(round.mode==='culture')return `<span class="culture-icon" role="img" aria-label="Símbolo de ${escape(round.word[0])}">${escape(round.word[2])}</span>`;const i=round.imageIndex;if(i===113||i===114)return `<span class="word-image extra-word" role="img" aria-label="Ilustración de ${escape(round.word[0])}" style="background-position:${i===113?0:100}% 50%"></span>`;return `<span class="word-image" role="img" aria-label="Ilustración de ${escape(round.word[0])}" style="background-position:${(i%12)*100/11}% ${Math.floor(i/12)*100/11}%"></span>`;}
const app=document.getElementById('app');let players=[],phase='setup',turn=0,round=null,used=new Set(),difficulty='family',scores=Object.create(null),vote=[],impostorCount=1,resetArmed=false,roleCounts=Object.create(null),lastImpostors=[],previousImpostors=[],returnPhase='handoff',megaWinners=[],celebration=false,celebrants=[];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function saveScores(){try{localStorage.setItem('impostor-family-session',JSON.stringify({players,scores,difficulty,impostorCount,roleCounts,lastImpostors,previousImpostors,megaWinners}));}catch{}}
function pointsFor(name){return Number.isSafeInteger(scores[name])&&scores[name]>=0?scores[name]:0;}
function leaderboard(){if(!players.length)return '';const rows=players.map((name,i)=>({name,i,points:pointsFor(name)})).sort((a,b)=>b.points-a.points);const top=rows[0].points;const leaders=rows.filter(p=>p.points===top).map(p=>p.name);return `<section class="scoreboard"><div class="score-heading"><strong>Marcador</strong><span>${top>0?(leaders.length===1?'Va ganando':'Empatan'):'¡Todo por jugar!'}</span></div>${top>0?`<p class="leader">${leaders.map(escape).join(' · ')}</p>`:''}<ol>${rows.map(p=>`<li>${avatar(p.i)}<span>${escape(p.name)}</span><strong>${p.points} <small>pts</small></strong></li>`).join('')}</ol>${phase==='setup'&&top>0?`<button class="quiet" id="reset-scores">${resetArmed?'Confirmar: borrar todos los puntos':'Reiniciar marcador'}</button>`:''}</section>`;}
function settle(){if(round.scored)return;const caught=round.impostors.every(i=>vote.includes(i));const individual=(round.firstBallots||[]).filter(b=>!round.impostors.includes(b.voter)&&b.picks.some(i=>round.impostors.includes(i))).map(b=>players[b.voter]);round.winners=[...new Set([...individual,...(caught?[]:round.impostors.map(i=>players[i]))])];round.caught=caught;celebrants=[];for(const name of round.winners){const before=pointsFor(name);scores[name]=before+round.points;if(before<20&&scores[name]>=20&&!megaWinners.includes(name)){megaWinners.push(name);celebrants.push(name);}}celebration=celebrants.length>0;round.scored=true;saveScores();}
try{const saved=JSON.parse(localStorage.getItem('impostor-family-session')||'null');if(saved&&Array.isArray(saved.players)&&saved.players.length<=20&&saved.players.every(p=>typeof p==='string'&&p.trim()&&p.length<=24)&&new Set(saved.players).size===saved.players.length){players=saved.players;scores=Object.fromEntries(players.map(p=>[p,Number.isSafeInteger(saved.scores?.[p])&&saved.scores[p]>=0?saved.scores[p]:0]));megaWinners=Array.isArray(saved.megaWinners)?saved.megaWinners.filter(n=>players.includes(n)):[];roleCounts=Object.fromEntries(players.map(p=>[p,Number.isSafeInteger(saved.roleCounts?.[p])&&saved.roleCounts[p]>=0?saved.roleCounts[p]:0]));lastImpostors=Array.isArray(saved.lastImpostors)?saved.lastImpostors.filter(n=>players.includes(n)):[];previousImpostors=Array.isArray(saved.previousImpostors)?saved.previousImpostors.filter(n=>players.includes(n)):[];difficulty=['family','hard','culture'].includes(saved.difficulty)?saved.difficulty:'family';impostorCount=Number.isInteger(saved.impostorCount)?Math.max(1,Math.min(saved.impostorCount,players.length-2)):1;}}catch{}
function random(n){const a=new Uint32Array(1);const limit=4294967296-4294967296%n;do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%n;}
// Sorteo sin reemplazo: se priorizan quienes no fueron impostores en la última ronda.
function chooseImpostors(){
 const chosen=[];let remaining=players.map((_,i)=>i);
 for(let slot=0;slot<impostorCount;slot++){
  const fresh=remaining.filter(i=>!lastImpostors.includes(players[i]));
  const pool=fresh.length?fresh:remaining;
  const weights=pool.map(i=>{const name=players[i];const count=Number.isSafeInteger(roleCounts[name])?roleCounts[name]:0;return Math.max(1,Math.floor(120/(1+count)/(previousImpostors.includes(name)?3:1)));});
  let ticket=random(weights.reduce((sum,w)=>sum+w,0)),pick=pool[pool.length-1];
  for(let i=0;i<pool.length;i++){if(ticket<weights[i]){pick=pool[i];break;}ticket-=weights[i];}
  chosen.push(pick);remaining=remaining.filter(i=>i!==pick);
 }
 previousImpostors=[...lastImpostors];lastImpostors=chosen.map(i=>players[i]);
 for(const name of lastImpostors)roleCounts[name]=(Number.isSafeInteger(roleCounts[name])?roleCounts[name]:0)+1;
 saveScores();return chosen;
}
function goToMenu(){
 celebration=false;celebrants=[];
 document.getElementById('veil').classList.add('hidden');
 if(phase==='setup')return;
 if(phase==='result'){phase='setup';round=null;vote=[];resetArmed=false;render();return;}
 if(phase==='exit')return;
 returnPhase=phase==='secret'?'handoff':phase==='ballot'?'vote-handoff':phase;phase='exit';render();
}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function beginVoting(){round.ballots=[];round.firstBallots=null;round.locked=[];round.voteCandidates=players.map((_,i)=>i);round.voteSeats=round.impostors.length;round.runoff=false;round.voter=0;round.picks=[];phase='vote-handoff';render();}
function submitBallot(){if(round.picks.length!==round.voteSeats)return;round.ballots.push({voter:round.voter,picks:[...round.picks]});round.picks=[];round.voter++;if(round.voter<players.length){phase='vote-handoff';render();return;}tallyVotes();}
function tallyVotes(){
 if(!round.firstBallots)round.firstBallots=round.ballots.map(b=>({voter:b.voter,picks:[...b.picks]}));
 const counts=players.map(()=>0);
 for(const ballot of round.ballots){if(round.impostors.includes(ballot.voter))continue;for(const pick of ballot.picks)counts[pick]++;}
 round.tally=counts;
 const ranked=[...round.voteCandidates].sort((a,b)=>counts[b]-counts[a]);
 const cut=counts[ranked[round.voteSeats-1]];
 const fixed=ranked.filter(i=>counts[i]>cut),tied=ranked.filter(i=>counts[i]===cut);
 const slots=round.voteSeats-fixed.length;
 if(tied.length>slots){round.locked.push(...fixed);round.voteCandidates=tied;round.voteSeats=slots;phase='vote-tie';}
 else{vote=[...round.locked,...fixed,...tied];phase='vote-summary';}
 render();
}
function tallyCard(){return `<section class="scoreboard"><strong>Votos válidos${round.runoff?' del desempate':''}</strong><ol>${players.map((name,i)=>({name,i,count:round.tally[i]})).filter(p=>round.voteCandidates.includes(p.i)).sort((a,b)=>b.count-a.count).map(p=>`<li>${avatar(p.i)}<span>${escape(p.name)}</span><strong>${p.count}</strong></li>`).join('')}</ol></section>`;}
function megaOverlay(){return `<section class="mega-overlay" role="dialog" aria-modal="true" aria-labelledby="mega-title"><div class="fireworks" aria-hidden="true">${Array.from({length:48},(_,i)=>`<span style="--angle:${i%12*30}deg;--radius:${80+i%3*28}px;--x:${[22,75,32,65][Math.floor(i/12)]}%;--y:${[22,28,66,73][Math.floor(i/12)]}%;--delay:${Math.floor(i/12)*.35}s;--spark:${['#d6f76d','#ffb19f','#77dcff','#d5a1ff'][i%4]}"></span>`).join('')}</div><div class="mega-content"><div class="mega-trophy" aria-hidden="true">🏆</div><span class="eyebrow">¡20 puntos o más!</span><h2 id="mega-title">${celebrants.length===1?'¡Eres el mega ganador!':'¡Son los mega ganadores!'}</h2><div class="mega-names">${celebrants.map(escape).join(' · ')}</div><p>${celebrants.map(n=>`${escape(n)}: ${pointsFor(n)} puntos`).join('<br>')}</p><button class="primary" id="mega-continue">Seguir celebrando y jugando</button><button class="secondary" id="mega-menu">Menú principal</button></div></section>`;}
function render(){
 impostorCount=Math.max(1,Math.min(impostorCount,players.length-2));
 if(phase==='setup'){
 app.innerHTML=`<div><h1>El impostor<span style="color:#d6f76d">.</span></h1><p>Una palabra. Un secreto.<br>¿Quién está disimulando?</p><section class="panel"><label class="label" for="name">¿Quiénes juegan?</label><form id="names" class="entry"><input id="name" maxlength="24" autocomplete="off" placeholder="Nombre del participante" aria-describedby="error"><button class="add" aria-label="Agregar participante">+</button></form><div id="error" class="error" role="status"></div><div class="list">${players.map((p,i)=>`<span class="chip">${avatar(i)}${escape(p)}<button class="remove" data-remove="${i}" aria-label="Quitar a ${escape(p)}">×</button></span>`).join('')}</div></section><span class="count">${players.length} participantes · mínimo 3</span><fieldset class="difficulty"><legend>Elige la ronda</legend><div class="mode-options"><button type="button" class="mode ${difficulty==='family'?'selected':''}" id="family" aria-pressed="${difficulty==='family'}">Para todos<span>Palabras de todos los días · 1 punto</span></button><button type="button" class="mode ${difficulty==='hard'?'selected':''}" id="hard" aria-pressed="${difficulty==='hard'}">Súper difícil<span>Palabras poco comunes · 3 puntos</span></button><button type="button" class="mode ${difficulty==='culture'?'selected':''}" id="culture" aria-pressed="${difficulty==='culture'}">Cultura general<span>Personas, países y lugares · 1 punto</span></button></div></fieldset><label class="impostor-setting" for="impostor-count"><span>¿Cuántos impostores?</span><select id="impostor-count" ${players.length<3?'disabled':''}>${Array.from({length:Math.max(1,players.length-2)},(_,i)=>`<option value="${i+1}" ${impostorCount===i+1?'selected':''}>${i+1}</option>`).join('')}</select></label><p class="note">Siempre quedan al menos 2 personas con la palabra.</p>${leaderboard()}</div><div class="bottom"><button class="primary" id="start" ${players.length<3?'disabled':''}>Empezar la ronda</button><p class="note">${impostorCount} ${impostorCount===1?'impostor':'impostores'} con pista · ${difficulty==='hard'?'reto para los valientes':difficulty==='culture'?'aprendemos jugando':'palabras para todos'}</p></div>`;
 document.getElementById('names').addEventListener('submit',e=>{e.preventDefault();try{addPlayer(document.getElementById('name').value);}catch{}});
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{players.splice(Number(b.dataset.remove),1);saveScores();render();});document.getElementById('impostor-count').addEventListener('change',e=>{impostorCount=Number(e.target.value);saveScores();render();});bind('reset-scores',()=>{if(!resetArmed){resetArmed=true;render();return;}scores=Object.create(null);megaWinners=[];celebration=false;celebrants=[];resetArmed=false;saveScores();render();});bind('start',start);bind('family',()=>{difficulty='family';saveScores();render();});bind('hard',()=>{difficulty='hard';saveScores();render();});bind('culture',()=>{difficulty='culture';saveScores();render();});
 }else if(phase==='exit'){
 app.innerHTML=`<span class="eyebrow">Menú principal</span><h2>¿Salir de esta ronda?</h2><p>La ronda actual se cancela sin sumar puntos. Los nombres y el marcador se conservan.</p><div class="bottom"><button class="primary" id="exit-yes">Volver al menú</button><button class="secondary" id="exit-no">Seguir la ronda</button></div>`;
 bind('exit-yes',()=>{phase='setup';round=null;vote=[];resetArmed=false;saveScores();render();});bind('exit-no',()=>{phase=returnPhase;render();});
 }else if(phase==='handoff'||phase==='secret'){
 const p=players[turn],is=round.impostors.includes(turn),secret=phase==='secret';
 app.innerHTML=`<div class="progress" aria-label="Participante ${turn+1} de ${players.length}"><span style="width:${(turn+1)/players.length*100}%"></span></div><span class="eyebrow">${turn+1} de ${players.length}</span><div class="turn-person">${avatar(turn,true)}<h2>Turno de ${escape(p)}</h2></div><p>${secret?'Mira tu secreto y luego ocúltalo.':'Pásale el celular. Solo esta persona debe mirar.'}</p><section class="card">${!secret?'<div class="symbol">?</div><strong>¿Tienes el celular?</strong>':is?`<span class="eyebrow impostor">Eres el impostor</span><h2 class="impostor">¡Disimula!</h2><p style="margin-bottom:8px">Tu pista</p><div class="hint">${escape(round.word[1])}</div>`:`<span class="eyebrow">Tu palabra</span>${wordImage()}<div class="secret">${escape(round.word[0])}</div><span class="count">Da una pista sin decir la palabra.</span>`}</section><div class="bottom"><button class="primary" id="action">${secret?'Ocultar y continuar':'Revelar mi secreto'}</button><p class="note">${secret?'Guarda tu secreto. No lo digas en voz alta.':'Que los demás no vean la pantalla.'}</p></div>`;
 bind('action',()=>{if(!secret)phase='secret';else{turn++;phase=turn===players.length?'play':'handoff';}render();});
 }else if(phase==='play'){
 app.innerHTML=`<span class="eyebrow">Todos tienen su secreto</span><h2>¡A dar pistas!</h2><div class="card"><span class="count">Empieza</span>${avatar(round.starter,true)}<div class="secret">${escape(players[round.starter])}</div><span class="count">Después sigan alrededor de la mesa.</span></div><div class="rule"><span class="num">1</span><span>Cada uno da una pista sin decir la palabra.</span></div><div class="rule"><span class="num">2</span><span>Después de las pistas, cada persona vota en secreto. Los votos de los impostores no cuentan.</span></div><p class="points-note">Acertar con tu voto vale ${round.points} ${round.points===1?'punto':'puntos'}. Si el grupo falla, los impostores también suman.</p>${leaderboard()}<div class="bottom"><button class="secondary" id="finish">Empezar la votación</button></div>`;bind('finish',beginVoting);
 }else if(phase==='vote-handoff'){
 app.innerHTML=`<span class="eyebrow">Votación ${round.runoff?'de desempate':''} · ${round.voter+1} de ${players.length}</span><div class="turn-person">${avatar(round.voter,true)}<h2>Vota ${escape(players[round.voter])}</h2></div><p>Pásale el celular. Su voto es secreto.</p><div class="card"><div class="symbol">?</div><strong>Solo esta persona debe mirar.</strong></div><div class="bottom"><button class="primary" id="open-ballot">Ver candidatos</button></div>`;
 bind('open-ballot',()=>{phase='ballot';render();});
 }else if(phase==='ballot'){
 app.innerHTML=`<span class="eyebrow">Voto secreto ${round.runoff?'· desempate':''}</span><h2>${escape(players[round.voter])}, ¿quién sospechas?</h2><p>${round.voteSeats===1?'Elige una persona.':`Elige ${round.voteSeats} personas.`} Todos votan; los votos de los impostores se descartan al contar.</p><span class="count">${round.picks.length} de ${round.voteSeats} seleccionados</span><div class="vote-list">${round.voteCandidates.map(i=>`<button class="vote ${round.picks.includes(i)?'selected':''}" data-ballot="${i}" aria-pressed="${round.picks.includes(i)}">${avatar(i)}${escape(players[i])}</button>`).join('')}</div><div class="bottom"><button class="primary" id="submit-ballot" ${round.picks.length!==round.voteSeats?'disabled':''}>Guardar voto y ocultar</button></div>`;
 app.querySelectorAll('[data-ballot]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.ballot);if(round.picks.includes(i))round.picks=round.picks.filter(p=>p!==i);else if(round.picks.length<round.voteSeats)round.picks.push(i);render();});bind('submit-ballot',submitBallot);
 }else if(phase==='vote-tie'){
 app.innerHTML=`<span class="eyebrow">Hay un empate</span><h2>¡A desempatar!</h2><p>Vuelvan a votar entre las personas empatadas. Los votos de los impostores siguen sin contar. Los puntos personales se calculan con el primer voto.</p>${tallyCard()}<div class="bottom"><button class="primary" id="runoff">Votar el desempate</button></div>`;
 bind('runoff',()=>{round.ballots=[];round.voter=0;round.picks=[];round.runoff=true;phase='vote-handoff';render();});
 }else if(phase==='vote-summary'){
 app.innerHTML=`<span class="eyebrow">Votación terminada</span><h2>Los más votados</h2><p>${vote.map(i=>escape(players[i])).join(' · ')}</p>${tallyCard()}<p class="note">Los votos de los impostores no se contaron. Cada voto válido valió lo mismo.</p><div class="bottom"><button class="primary" id="reveal">Revelar y sumar puntos</button></div>`;
 bind('reveal',()=>{settle();phase='result';render();});

 }else{
 app.innerHTML=`<span class="eyebrow">Se acabó el misterio</span><h2>${round.impostors.length===1?'El impostor era…':'Los impostores eran…'}</h2><div class="card"><div class="impostor-reveal">${round.impostors.map(i=>`<div>${avatar(i,true)}<div class="impostor-name">${escape(players[i])}</div></div>`).join('')}</div><span class="count">La palabra era</span>${wordImage()}<div class="hint" style="margin:10px 0">${escape(round.word[0])}</div><span class="count">Pista: ${escape(round.word[1])}</span></div>${curiousCard()}<div class="winners"><strong>${round.caught?(round.impostors.length===1?'¡Descubrieron al impostor!':'¡Descubrieron a todos!'):(round.impostors.length===1?'¡El impostor los engañó!':'¡Los impostores ganaron!')}</strong><p>${round.winners.map(escape).join(', ')} ${round.winners.length===1?'gana':'ganan'} ${round.points} ${round.points===1?'punto':'puntos'}.</p></div>${leaderboard()}<div class="bottom"><button class="primary" id="again">Otra ronda</button><button class="secondary" id="switch">${difficulty==='hard'?'Ronda para todos':'Ronda súper difícil'}</button><button class="quiet" id="edit">Cambiar ronda o participantes</button></div>`;bind('again',start);bind('switch',()=>{difficulty=difficulty==='hard'?'family':'hard';saveScores();start();});bind('edit',goToMenu);
 }
 if(celebration&&phase==='result'){app.innerHTML+=megaOverlay();bind('mega-continue',()=>{celebration=false;render();});bind('mega-menu',goToMenu);document.getElementById('mega-continue')?.focus();}
}
function addPlayer(value){const n=value.trim().replace(/\s+/g,' ');let error='';if(!n)error='Escribe un nombre para agregarlo.';else if(n.length>24)error='Usa un nombre de hasta 24 letras.';else if(players.some(p=>p.toLocaleLowerCase('es')===n.toLocaleLowerCase('es')))error='Ese nombre ya está. Agrega un apellido o apodo.';else if(players.length>=20)error='Pueden jugar hasta 20 participantes.';if(error){const el=document.getElementById('error');if(el)el.textContent=error;throw new Error(error);}players.push(n);saveScores();render();document.getElementById('name')?.focus();return {participants:players.length};}
function start(){if(players.length<3)throw new Error('Se necesitan al menos 3 participantes.');const bank=difficulty==='hard'?hardWords:difficulty==='culture'?cultureWords:words;const prefix=difficulty+':';let options=bank.map((_,i)=>i).filter(i=>!used.has(prefix+i));if(!options.length){for(const key of used){if(key.startsWith(prefix))used.delete(key);}options=bank.map((_,i)=>i);}const index=options[random(options.length)];used.add(prefix+index);vote=[];const selectedImpostors=chooseImpostors();round={mode:difficulty,points:difficulty==='hard'?3:1,scored:false,word:bank[index],imageIndex:difficulty==='hard'?words.length+index:index,impostors:selectedImpostors,starter:random(players.length)};turn=0;phase='handoff';render();return{phase,participants:players.length};}
// Al cambiar de aplicación se oculta el secreto hasta regresar a la pantalla de entrega.
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(phase==='secret'||phase==='ballot')){phase=phase==='secret'?'handoff':'vote-handoff';render();document.getElementById('veil').classList.remove('hidden');}});bind('resume',()=>document.getElementById('veil').classList.add('hidden'));bind('menu-home',goToMenu);
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_participants',description:'Configura los nombres antes de empezar una ronda. Solo funciona en la pantalla de participantes.',inputSchema:{type:'object',properties:{names:{type:'array',items:{type:'string'},minItems:3,maxItems:20}},required:['names'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(phase!=='setup')throw new Error('Termina la ronda antes de cambiar participantes.');if(!input||!Array.isArray(input.names)||input.names.length<3||input.names.length>20)throw new Error('Se necesitan entre 3 y 20 nombres.');const next=input.names.map(n=>{if(typeof n!=='string'||!n.trim()||n.trim().length>24)throw new Error('Nombre inválido.');return n.trim().replace(/\s+/g,' ');});if(new Set(next.map(n=>n.toLocaleLowerCase('es'))).size!==next.length)throw new Error('Los nombres deben ser distintos.');players=next;saveScores();render();return{participants:players.length};}})).catch(()=>{});}catch{}}
